### ISSUE TITLE
EPIC: Improve release process

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#1039]
## Problem

This EPIC is used to track the work around improving the release process of ICS. 

## Closing criteria

All the tasks below are completed.

## Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/801
- [ ] https://github.com/cosmos/interchain-security/issues/1216
- [ ] https://github.com/cosmos/interchain-security/issues/1035
```

```[tasklist]
### Nice to have

```

**Comment by mpoke** [comment]
Closing for now as completed.
