### ISSUE TITLE
prepare and cut ICS v3 

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#1042]
## Problem

Prepare and cut ICS v3 which uses cosmos-sdk v0.47 and ibc-go v7.

## Closing criteria

- [x] merge [feat/upgrade-ics-sdk47-ibc7](https://github.com/cosmos/interchain-security/tree/feat/upgrade-ics-sdk47-ibc7) into main
- [x] (#1043) update code and go.mod to reference `interchain-security/v3` instead of `interchain-security/v2`
- [x] create `release/v3.x.x` branch
- [x] (#1046)update branch protection rules an CI workflow files to also track `release/v3.x.x`
- [x] create changelog for `v3.0.0`
- [x] create first release candidate `v3.0.0-rc0`
- [ ] ~resolve: https://github.com/cosmos/interchain-security/issues/1105 -> not resolved, issue remains open since it required nuanced changes to CCV protocol~
- [x] cut final `v3.0.0` -> [Release](https://github.com/cosmos/interchain-security/releases/tag/v3.0.0)
