### ISSUE TITLE
EPIC: ICS backlog Q-3.23

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#1086]
## Problem

This is a meta issue used to track the work on ICS backlog issues during Q3 2023.  

## Closing criteria

The completion of Q3 2023.

## Issues

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/603
- [ ] https://github.com/cosmos/interchain-security/issues/497
- [ ] https://github.com/cosmos/interchain-security/issues/690
- [ ] https://github.com/cosmos/interchain-security/issues/939
- [ ] https://github.com/cosmos/interchain-security/issues/546
- [ ] https://github.com/cosmos/interchain-security/issues/547
- [ ] https://github.com/cosmos/interchain-security/issues/362
- [ ] https://github.com/cosmos/interchain-security/issues/894
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/568
- [ ] https://github.com/cosmos/interchain-security/issues/678
```

**Comment by mpoke** [comment]
Closing as no longer useful. The project board should be used to track the backlog.
