### ISSUE TITLE
EPIC: ICS protocol requires a lot of packets to be relayed

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#1087]
## Problem

In every block that the provider valset changes, a `VSCPacket` must be sent to every consumer and a corresponding `VSCMaturedPacket` sent back. Given that the validator powers may change very often on the provider chain (e.g., the Cosmos Hub), this approach results in a large workload for the relayers. 

This EPIC is used to track the work on this issue.  

## Closing criteria

- [x] A decision is reached on whether this issue is a concern.
- [x] If the issue is a concern, a solution is implemented. 

## Task list

```[tasklist]
### Must have
- [x] Discuss whether a solution is needed (if not, close EPIC)
- [x] Come up with a potential solution
- [ ] https://github.com/cosmos/interchain-security/issues/1514
- [ ] https://github.com/cosmos/interchain-security/issues/1515
- [ ] https://github.com/cosmos/interchain-security/issues/1516
- [x] update docs
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/718
```
