### ISSUE TITLE
Revigorate difftests

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#1176]
## Problem

The difftests are outdated. When we regenerate traces, they typically cannot be run and simply fail.
This issue lists the work necessary to revigorate the model.

## Closing criteria

- [x] #1177
- [ ] https://github.com/cosmos/interchain-security/issues/1193
- [ ] The traces are regenerated at least nightly
- [ ] Running the traces gives close to no false positive bug reports
- [ ] The team is able to read the model, and can request and collaborate on necessary model modifications

**Comment by p-offtermatt** [comment]
Closing this for now, see https://github.com/cosmos/interchain-security/issues/1177
