### ISSUE TITLE
support cosmos-sdk with LSM changes in ICS v2

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#1183]
## Summary

This [thread](https://forum.cosmos.network/t/plan-software-upgrade-deploy-lsm-on-the-cosmos-hub/10876) on the forum and the resulting [governance proposal](https://www.mintscan.io/cosmos/proposals/790) requires that the LSM be included on Gaia.

## Problem Definition

Since Gaia is an ICS provider the ICS functionality must be maintained and no liveness or safety concerns regarding ICS integrating with LSM should be left unadressed.

To achieve this goal some features from ICS v3 (using cosmos-sdk v47) must be backported to ICS v2.
Since the changes are state breaking this would most likely yield in releasing `ICS v2.1` that supports the LSM feature.

## Proposal

Backport fixes, features and testing from ICS v3 into v2 to support LSM:

1. backport `CancelUnbonding` special handling. Context listed below:
    * https://github.com/cosmos/cosmos-sdk/issues/12931
    * https://github.com/cosmos/cosmos-sdk/pull/12967
    * https://github.com/cosmos/cosmos-sdk/issues/16042
    * https://github.com/cosmos/interchain-security/issues/1045
    * https://github.com/cosmos/interchain-security/pull/1019

2. backport tests
    * add support to the "old" e2e test suite
    * backport integration tests

## Task list

```[tasklist]
### Must have
- [ ] backport `CancelUnbonding`
- [ ] backport tests for `CancelUnbonding`
- [ ] release `v2.1`
```

```[tasklist]
### Nice to have
- [ ] add sub-tasks that are nice to have for the proposed feature
```

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?
