### ISSUE TITLE
EPIC: Model-Based Testing using the Quint model

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#1238]
## Problem

The existing difftest model is unmaintained. We want an alternative approach to automatically generating test traces.

## Closing criteria

We have a minimal prototype for MBT of ICS using the Quint model.
It allows
* generating traces, and
* replaying traces

## Problem details

The goal of this epic is to get a proof-of-concept prototype of model-based testing for interchain security.
The key outcome of this epic is data on the effort/reward ratio of model-based testing, and generally to get experience with the MBT approach. Accordingly, this epics deliverable is a minimal prototype.

A secondary goal is also to improve our confidence:
a) in the correctness of the model
b) in the alignment of the code with the model
c) and thus in the correctness of the code

The confidence increase in the correctness of the implementation is not the main outcome of the epic - the part of interchain security that the model deals with is already well tested (it is running in production!).
It is rather to try out this approach and get familiar with it, to judge whether this is something we want to incorporate more deeply e.g. when we make changes to the protocol, where increasing our confidence is crucial.

## Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/1239
- [ ] https://github.com/cosmos/interchain-security/issues/1240
- [ ] https://github.com/cosmos/interchain-security/issues/1241
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/318
- [ ] https://github.com/cosmos/interchain-security/issues/319
- [ ] https://github.com/cosmos/interchain-security/issues/534
- [ ] https://github.com/cosmos/interchain-security/issues/691
- [ ] https://github.com/cosmos/interchain-security/issues/1044
- [ ] https://github.com/cosmos/interchain-security/issues/306
- [ ] https://github.com/cosmos/interchain-security/issues/1131
```
