### ISSUE TITLE
SDK 50 upgrade

### ISSUE THREAD

**Issue by faddat** [cosmos/interchain-security#1246]
## Problem

Given the improvements to node performance in SDK 50, it makes sense for consumer chains to upgrade to 50.

## Closing criteria

A single PR is submitted to a upgrade feature branch, which upgrades the repository in one go against that branch to prevent problems midstream with  compatibility of different pieces of code that live in this repository.

## Problem details

Now that IBC is upgraded, this should be relatively straightforward.

As long as the informal team thinks that it's appropriate, the notional team would like to complete this upgrade, as the notional team is attempting to ship various pieces of work with SDK 50.

```[tasklist]
### Tasks
- [x] spike: upgrade ICS to SDK 0.50 and IBC 8 (spike/v50-upgrade branch)
- [ ] https://github.com/cosmos/interchain-security/issues/1045
- [ ] https://github.com/cosmos/interchain-security/issues/1329
- [ ] https://github.com/cosmos/interchain-security/issues/1330
- [x] upgrade CometMock to Comet 0.38 https://github.com/informalsystems/CometMock/issues/62
- [ ] https://github.com/cosmos/interchain-security/issues/1349
- [ ] https://github.com/cosmos/interchain-security/issues/1352
- [ ] https://github.com/cosmos/interchain-security/issues/1359
- [ ] https://github.com/cosmos/interchain-security/issues/1356
- [ ] https://github.com/cosmos/interchain-security/issues/1353
- [ ] https://github.com/cosmos/interchain-security/issues/1361
- [ ] https://github.com/cosmos/interchain-security/issues/1378
- [ ] https://github.com/cosmos/interchain-security/issues/1380
- [ ] https://github.com/cosmos/interchain-security/issues/1780
- [ ] https://github.com/cosmos/interchain-security/issues/1818
```

**Comment by mpoke** [comment]
> Now that IBC is upgraded

Note that the ETA for the IBC release with SDK 0.50 is end of September. The plan is to also upgrade ICS by then.

**Comment by faddat** [comment]
Yep, it will take some time to fully finish the IBC release.

Prior to that we've been working on various upgrades --

* interchaintest
* ibc-apps
* wasmd

ICT and IBC are done enough to begin work on ICS, if you'd like.  Since
we'll be supporting other teams in this, it is likely that we'll just begin
the work, but please feel no need for our team to "own" that work.

**Comment by jtieri** [comment]
hello, i was curious if this was still prioritized for Q1? 

[interchaintest](https://github.com/strangelove-ventures/interchaintest) is blocked on introducing ICS support to its main branch (which currently makes use of ibc-go v8 and sdk v0.50.0) until then so figured i would check in on the current progress/prioritization

**Comment by mpoke** [comment]
> hello, i was curious if this was still prioritized for Q1?
> 
> [interchaintest](https://github.com/strangelove-ventures/interchaintest) is blocked on introducing ICS support to its main branch (which currently makes use of ibc-go v8 and sdk v0.50.0) until then so figured i would check in on the current progress/prioritization

Hi @jtieri. Yes, we plan to cut an alpha release soon.

**Comment by MSalopek** [comment]
Completed a while ago, closing.

Releases:
* https://github.com/cosmos/interchain-security/releases/tag/v5.1.0
* https://github.com/cosmos/interchain-security/releases/tag/v5.0.0
