### ISSUE TITLE
EPIC: Expand MBT functionality

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#1528]
## Problem

We want to expand the MBT model to cover more functionality.

## Closing criteria

We are running MBT for at least the must-have features.

## Problem details

For each of the features listed below, several main tasks have to be done:
1) Adjust the Quint model to include the feature
2) Add tests in Quint to test the feature
3) Make sure that the generated traces use the feature in non-trivial ways (or add new generation methods, i.e. invariants, that do)
4) Expand the driver to understand/utilize the new feature

## Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/1529
- [ ] https://github.com/cosmos/interchain-security/issues/1531
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/1532
- [ ] https://github.com/cosmos/interchain-security/issues/1530
```

```[tasklist]
### Other nice-to-have tasks related to MBT
- [ ] https://github.com/cosmos/interchain-security/issues/318
- [ ] https://github.com/cosmos/interchain-security/issues/319
- [ ] https://github.com/cosmos/interchain-security/issues/534
- [ ] https://github.com/cosmos/interchain-security/issues/691
- [ ] https://github.com/cosmos/interchain-security/issues/1044
- [ ] https://github.com/cosmos/interchain-security/issues/306
- [ ] https://github.com/cosmos/interchain-security/issues/1131
```
