### ISSUE TITLE
[Epic]:  Fault Resolutions

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#2088]
## Problem

A Fault Resolution mechanism has to be implemented to address the [subset problem](https://docs.google.com/document/d/1inRaSmBtyD71Ensa9VdjGeOo6NnPZ7DaWr6ZYA6zlPY/edit) in Opt-in consumer chains.

## Closing criteria

The following issues are resolved. 

## Task list

```[tasklist]
### Must have
- [ ] Introduce ADR for fault resolutions https://github.com/cosmos/interchain-security/pull/2051
- [ ] Record consumer validators subscription timestamps
- [ ] Add fault resolution mechanism
- [ ] Add E2E testing for incorrect executions
```
