### ISSUE TITLE
EPIC: Permissionless ICS

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#2108]
## Problem

This is a meta issue to track the work of [Permissinoless ICS](https://github.com/cosmos/interchain-security/blob/main/docs/docs/adrs/adr-018-permissionless-ics.md). Permissionless ICS allows _Opt In_ consumer chains to join ICS by simply issuing transactions, without having to go through a governance proposal.

## Task list

```[tasklist]
### Introduce new messages
- [x] new `MsgCreateConsumer` and `MsgUpdateConsumer` messages
```

```[tasklist]
### Re-key state
- [x] change all messages by renaming `chainId` to `consumerId` and use accordingly but make sure the error mesasges point out that `consumerId` is now needed (e.g., all previously working `MsgOptIn` messages would now fail because there's no consumer chain with a `stride-1` `consumerId`)
- [x] fix (and add new) unit/integration refactored to take into account `consumerId` instead of `chainId`
- [ ] fix (and add new) E2E tests refactored to take into account `consumerId` instead of `chainId`
```

```[tasklist]
### Introduce new state
- [x] `consumerId` counter stores somewhere that is never recycled and always increments
- [x] (`consumerId` to `chainId`) needed for misbehavior evidence (e.g., `HandleConsumerDoubleVoting`)
- [x] (`clientId` to `consumerId`) to be able to find the right consumer chain when setting up a channel, etc.
- [x] potentially additional state for the phase of a consumer chain, e.g., whether it's registered, initialized, etc. so that instead of doing `GetConsumerClientId( ...)` to check if a chain has launched, we have something akin `IsLaunched(...)`
- [x] add `owner_address` for each consumer state
```

```[tasklist]
### Deprecate proposals
- [x] deprecate legacy consumer proposals. Specifically, deprecate `ConsumerAdditionProposal` which means getting rid of `ConsumerAdditionProposal`s and using just the `consumerId`s instead that flow around (e.g., when checking which chain to launch) (see [#2130](https://github.com/cosmos/interchain-security/pull/2130))
- [x] deprecate `MsgConsumerAddition` and replace with a proposal that contains both `MsgInitializeConsumer` and `MsgUpdateConsumer`
```

```[tasklist]
### Modify relayer (optional)
- [x] contact Hermes to use the `consumerId` instead of the `chainId` for misbehaviour messages (see [hermes#4153](https://github.com/informalsystems/hermes/issues/4153))
- [ ] https://github.com/cosmos/interchain-security/issues/2158
```

```[tasklist]
### Migrate
- [x] migrate the state of already-launched consumer chains
- [x] make sure ongoing `ConsumerAdditionProposals` get migrated as well
```

```[tasklist]
### Test
- [ ] think of test scenarios (similar to the _Inactive Validators_ work - see [`docs/docs/adrs/adr-017-allowing-inactive-validators.md`](https://github.com/cosmos/interchain-security/pull/2079/files#diff-0ee2f33a35fab71662e82ab7003d56cd13c05103e760918a48d7c44cfdd9f97c)) and implement those (e.g., existing consumer chain keeps working, etc.)
- [ ] give test scenarios to Hypha (i.e., things that could wrong, things to verify)
- [ ] test all queries work with `consumerId`s if they used `chainId`s previously
- [ ] verify we have checks on all the new fields that messages introduced (see [here](https://informalsystems.slack.com/archives/C055LKX623Z/p1722414960567829?thread_ts=1721998175.172089&cid=C055LKX623Z))
```
```[tasklist]
### Write docs
- [ ] Write ICS docs [here](https://cosmos.github.io/interchain-security/) on Permissionless
```

```[tasklist]
### Potpourri (so we do not forget)
- [x] You should not be able to opt in to the different chains with the same `chainId` (add this in the ADR as well)
- [ ] Search for `TODO (PERMISSIONLESS)` before cutting this
- [ ] Thorough look on where `chainID`, `chain ID`, appear in code & comments, etc. and replace with consumer id
- [x] Stopping the chain before the evidence goes through might not allow us to slash in a permissionless setting. Think more on that. (At the end, we removed the state of a consumer chain only after an unbonding period of time)
- [ ] Reduce duplicate code (see [comment](https://github.com/cosmos/interchain-security/pull/2164#discussion_r1726890742))
- [x] Potentiallly make the phases protobuf enums
- [ ] (fix this) https://github.com/cosmos/interchain-security/pull/2172/files#r1731328299
```

```[tasklist]
### Forge requirements (queries)
- [ ] https://github.com/cosmos/interchain-security/issues/2159
- [ ] https://github.com/cosmos/interchain-security/issues/2160
```
