### ISSUE TITLE
[Epic]: Refactor ICS reward distribution to address several issues

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#2286]
## Problem

The refactoring is needed to address several issues.

- Consumer chains with the canonical transfer channel to the provider on a different client than the CCV channel will not be able to distribute rewards to provider validators. This is due to [this check](https://github.com/cosmos/interchain-security/blob/v6.0.0/x/ccv/provider/ibc_middleware.go#L125). Note that this was not a problem before ICS v6.0.0.
- Consumer chains cannot send rewards in non-native denoms. For more details, see https://github.com/cosmos/interchain-security/issues/1634. 
- Although consumer chain creation is permissionless, consumers still need to go through governance to whitelist their native denoms to be allowed as ICS rewards.
- New consumer chains (that don't have a transfer channel to the provider before joining ICS) cannot whitelist their denoms for ICS rewards as the name of the transfer channel endpoint on the provider side is not yet known. This means that opted in validators will not receive rewards in the first weeks after launching the consumer until the gov prop whitelisting the denom passes. Moreover, once the gov prop passes, those rewards are not retroactively distributed and they remain in the provider module account. 

## Closing criteria

All the tasks below are completed. 

## Task list

```[tasklist]
### Identifying the source of ICS rewards
- [x] Enable consumers to add the `consumerId` to the transfer memo field. See [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-020-fungible-token-transfer/README.md#using-the-memo-field) for details. https://github.com/cosmos/interchain-security/pull/2290
- [x] Backport the memo solution to ICS v4.5.x for consumers running SDK 0.47.
- [x] Leave the `IdentifyConsumerIdFromIBCPacket` check for legacy consumers.
- [x] Add hardcoded mapping from known transfer channels and their consumer chains (e.g., channel-391 for Stride) as a patch until these chains upgrade to the new version. https://github.com/cosmos/interchain-security/pull/2288
```

```[tasklist]
### Permissionless denom allowlisting
- [x] Enable every consumer to allowlist at most **3** denoms. https://github.com/cosmos/interchain-security/issues/2298
- [x] In the IBC transfer middleware, accept per-consumer denoms only if the consumer is registered.
```

```[tasklist]
### Fix existing state
- [x] Write migration in Gaia's upgrade handler to distribute all the unaccounted known denoms from `consumer_rewards_pool`. https://github.com/cosmos/gaia/pull/3361
```

```[tasklist]
### Other issues
- [ ] https://github.com/cosmos/interchain-security/issues/2292
```
