### ISSUE TITLE
[Epic]: ICS v6.4.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#2382]
## Problem

This is a meta issue used to track the release of ICS v6.4.0

## Closing criteria

ICS v6.4.0-rc0 is cut.

## Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/2371
- [ ] https://github.com/cosmos/interchain-security/issues/2359
- [ ] https://github.com/cosmos/interchain-security/issues/2281
- [ ] https://github.com/cosmos/interchain-security/issues/1245
- [ ] https://github.com/cosmos/interchain-security/issues/1194
- [ ] https://github.com/cosmos/interchain-security/issues/2383
- [ ] https://github.com/cosmos/interchain-security/issues/2386
- [ ] https://github.com/cosmos/interchain-security/issues/2385
- [ ] https://github.com/cosmos/interchain-security/issues/2327
- [ ] https://github.com/cosmos/interchain-security/issues/2030
- [ ] https://github.com/cosmos/interchain-security/issues/2397
- [ ] https://github.com/cosmos/interchain-security/issues/894
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/2311
- [ ] https://github.com/cosmos/interchain-security/issues/2280
- [ ] https://github.com/cosmos/interchain-security/issues/2147
- [ ] https://github.com/cosmos/interchain-security/issues/531
- [ ] https://github.com/cosmos/interchain-security/issues/1269
```

**Comment by mpoke** [comment]
ICs v6.4.0-rc0 is out https://github.com/cosmos/interchain-security/releases/tag/v6.4.0-rc0
