### ISSUE TITLE
[Feature]: Customizable Slashing and Jailing

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#2383]
### Summary

Implement [ADR 020: Customizable Slashing and Jailing](https://cosmos.github.io/interchain-security/adrs/adr-020-cutomizable_slashing_and_jailing). 

### Proposed Feature

See https://cosmos.github.io/interchain-security/adrs/adr-020-cutomizable_slashing_and_jailing#decision

### Work Breakdown

```[tasklist]
#### Must have
- [x] discuss proposal (if proposal rejected, close EPIC)
- [x] create ADR (if ADR rejected, close EPIC)
- [ ] see steps in https://cosmos.github.io/interchain-security/adrs/adr-020-cutomizable_slashing_and_jailing#implementation
```

```[tasklist]
#### Nice to have
- [ ] add sub-tasks that are nice to have for the proposed feature
```
