### ISSUE TITLE
Client expiring results in panic on provider

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#435]
# Problem

This issue was found during the ICS mini-testnet.

Once the client to the consumer chain expires, every attempt to send a packet to the consumer will result in a panic on the provider. This is because `channelKeeper.SendPacket` is always called from `EndBlock`, which means that when it returns error, the provider panics. 

`SendPacket` when the client is expired: https://github.com/cosmos/ibc-go/blob/b1f494c643280c73f3696461abbb11a39303b190/modules/core/04-channel/keeper/packet.go#L73

Provider panics: https://github.com/cosmos/interchain-security/blob/6c0d718d8c59339d112feb5850589258a504756e/x/ccv/provider/keeper/relay.go#L166 and https://github.com/cosmos/interchain-security/blob/6c0d718d8c59339d112feb5850589258a504756e/x/ccv/provider/keeper/relay.go#L195

**Possible fix:** handle the `clienttypes.ErrClientNotActive` error in the CCV module. Probably a good idea to do so also on the consumer side. 

# Closing criteria

- [x] The issue described above is fixed. 
- [x] The packets that couldn't be sent due to a client being expired are collected and sent if the clients are being upgraded. 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by MSalopek** [comment]
Closed by #448

**Comment by MSalopek** [comment]
Some issues were rased on #448. Small refactoring is needed
