### ISSUE TITLE
Regression tests for faulty iterators

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#454]
# Problem
https://github.com/cosmos/interchain-security/pull/447 and https://github.com/cosmos/interchain-security/pull/459 fixed multiple iterators being implemented incorrectly. We need to go back and make sure all the fixes have an appropriate UT to prove out the "correct" functionality (some functionality was changed, some was not). Its a bit concerning that some of the previous UTs did not catch the bugs.

# Closing criteria
Make sure there is a unit test for each fix AND that the unit test would have failed for previous code behavior (only where behavior was changed). Here's [one example](https://github.com/cosmos/interchain-security/pull/434#issuecomment-1304883178) of a UT that should exist

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
@MSalopek Please can you take a look at this and the code and decide if this should be closed or if there is still work to do?

See

- https://github.com/cosmos/interchain-security/commit/e0cbf9a8f17cb03d03604954ef8685d82d518ea5#diff-993a06db0f6114ea2c41155cce2ac1d530bedebba2ba051b3f0a0e5c0834a01f

Thanks

**Comment by smarshall-spitzbart** [comment]
Thanks for checking into this. Note every iterator in our codebase should be tested against multiple consumers, multiple iterations, etc. via a unit or e2e test

**Comment by jtremback** [comment]
Also, we have identified some other issues with the ordering in iterators. We should probably go over iterators in general and add a lot more tests, including tests that the order in the order we expect.

**Comment by smarshall-spitzbart** [comment]
Here's the checklist of methods I've collected which use iterators in the [latest version](https://github.com/cosmos/interchain-security/pull/596/commits/9a04275e820ab38d8629b84937b76a38b9644de2) of the `iterators-to-arrays` branch, and therefore need to be regression tested to close this issue. Commits on top of the one referenced should add/subtract from this list if iterators are added/removed. 

These names were found by searching the repo for `KVStorePrefixIterator`, `KVStoreReversePrefixIterator`, `KVStorePrefixIteratorPaginated`, and `KVStoreReversePrefixIteratorPaginated`. If there's a flaw in the way I'm collecting these methods, lmk. Also, it may be useful to split up #596 by file and/or any PRs which add onto that branch. 

List:

### Consumer `keeper.go`
- [ ] GetElapsedPacketMaturityTimes
- [ ] GetAllPacketMaturityTimes
- [ ] GetAllHeightToValsetUpdateIDs
- [ ] GetAllOutstandingDowntimes
- [ ] GetAllCCValidator

### Provider `keeper.go`
- [ ] GetAllConsumerChains
- [ ] GetAllChannelToChains
- [ ] GetAllUnbondingOps
- [ ] GetAllUnbondingOpIndexes
- [ ] GetAllValsetUpdateBlockHeights
- [ ] GetAllInitTimeoutTimestamps
- [ ] GetAllVscSendTimestamps
- [ ] GetFirstVscSendTimestamp

### `key_assignment.go`
- [ ] GetAllValidatorConsumerPubKeys
- [ ] GetAllValidatorsByConsumerAddr
- [ ] GetAllKeyAssignmentReplacements
- [ ] GetAllConsumerAddrsToPrune

### `proposal.go`
- [ ] GetConsumerAdditionPropsToExecute
- [ ] GetAllPendingConsumerAdditionProps
- [ ] GetConsumerRemovalPropsToExecute
- [ ] GetAllPendingConsumerRemovalProps

### `throttle.go`
- [ ] GetAllGlobalSlashEntries
- [ ] GetSlashAndTrailingData
- [ ] GetAllThrottledPacketData (only used in tests)
- [ ] DeleteThrottledPacketDataForConsumer

### `export.go`
- [ ] prepForZeroHeightGenesis (auto generated code)

**Comment by mpoke** [comment]
The regression tests for 

-   GetConsumerAdditionPropsToExecute
-   GetAllPendingConsumerAdditionProps
-   GetConsumerRemovalPropsToExecute
-   GetAllPendingConsumerRemovalProps

will be added in the fix for https://github.com/cosmos/interchain-security/issues/537 as the tests fail without the fix.

**Comment by mpoke** [comment]
> Also, it may be useful to split up https://github.com/cosmos/interchain-security/pull/596 by file and/or any PRs which add onto that branch.

This would entail a lot of work :(

**Comment by smarshall-spitzbart** [comment]
@mpoke, with https://github.com/cosmos/interchain-security/pull/623, we should be good!

The only unchecked boxes are `GetAllThrottledPacketData` and `prepForZeroHeightGenesis` which both don't need tests
