### ISSUE TITLE
EPIC: Release v1.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#666]
# Tasks

- [x] Cut ICS v1.0.0-rc1  https://github.com/cosmos/interchain-security/releases/tag/v1.0.0-rc1
- [x] Code audit
- [x] Two weeks of testing in release testnet
- [x] Fix additional issues assign to `ICS v1.0.0` milestone (no changes to the ICS functionality)
- [x] Cut ICS v1.0.0

# Closing criteria

ICS v1.0.0 release is cut. 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project
