### ISSUE TITLE
EPIC: Standardize QA processes for ICS repo

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#678]
# Problem

Currently, there is a lack of structure / guidelines when it comes to ICS testing, both UTs and e2e tests.  

# Closing criteria

The following issues are resolved. 

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/interchain-security/issues/629
- [ ] https://github.com/cosmos/interchain-security/issues/506
- [ ] https://github.com/cosmos/interchain-security/issues/625
- [ ] https://github.com/cosmos/interchain-security/issues/604
- [ ] https://github.com/cosmos/interchain-security/issues/1165
```

**Comment by MSalopek** [comment]
Related:
https://github.com/cosmos/gaia/issues/2406
