### ISSUE TITLE
epic: release documentation

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#750]
# Problem
Documentation in ICS repo is lacking.

# Dev branch
https://github.com/cosmos/interchain-security/pull/759

# Related issues:

- [x] Close duplicate issues for docs
- [x] Add docusaurus to ICS repo
- [x] Add user centric introduction page
- [x] Add user centric FAQ page
- [x] Add consumer onboarding documentation (#742) <- moved from that PR to `meta/docs`
- [x] Reuse UI template from gaia/cosmos-sdk for consistency
- [x] https://github.com/cosmos/interchain-security/issues/377
- [x] In addition to above, migrate all uncategorized markdowns in `/docs` to docusaurus pages
- [ ] https://github.com/cosmos/interchain-security/issues/680 <- Onboarding page touches on this a bit, do we need more info?
- [x] add key assigmnent docs #770 
- [x] #772 
- [x] #771 
- [ ] Link or paste updated roadmap in website 
- [x] Deploy website, link to it in main README
- [x] ~Add info from diff testing README to website. We want to get rid of all extraneous docs right?~

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
As far next steps, we can go into in-depth concepts about the protocol within the docs website. But that content could mostly be copied from https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/README.md

**Comment by mpoke** [comment]
Closing as done. The result of this work is the docs page https://cosmos.github.io/interchain-security/
