### ISSUE TITLE
EPIC: Provider assumption of trusted consumer too strong

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#754]
# Problem

Currently, the provider assumes that the consumers are not malicious. Although the assumption is realistic for every consumer validator set (i.e., Replicated Security), the consumer may have malicious code. Thus, this assumption adds high requirements for the auditing process of consumer chains. 

# Closing criteria

The assumption of trusted consumer is dropped or relaxed. 

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/interchain-security/issues/417
- [ ] https://github.com/cosmos/interchain-security/issues/594
- [ ] https://github.com/cosmos/interchain-security/issues/634
- [ ] https://github.com/cosmos/interchain-security/issues/635
- [ ] https://github.com/cosmos/interchain-security/issues/566
- [ ] https://github.com/cosmos/interchain-security/issues/261
```

**Comment by mpoke** [comment]
Replaced by https://github.com/cosmos/interchain-security/issues/732 and https://github.com/cosmos/interchain-security/issues/761
