### ISSUE TITLE
EPIC: Standalone to consumer changeover

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#756]
# Problem

https://github.com/cosmos/interchain-security/pull/697 gave us an awesome implementation of https://github.com/cosmos/ibc/pull/840. There are remaining tasks that we need to get into a release for Stride's standalone to consumer changeover

# Closing criteria

The below tasks are completed and merged into main, where all comments from https://github.com/cosmos/interchain-security/pull/697 are addressed. 

In accomplishing all these tasks, we should try our best to make the changes affect the consumer only.

# Task list

```[tasklist]
### Must have
- [x] Initial implementation is merged, follows ICS patterns -> https://github.com/cosmos/interchain-security/pull/757
- [ ] https://github.com/cosmos/interchain-security/issues/783
- [ ] https://github.com/cosmos/interchain-security/issues/781
- [ ] https://github.com/cosmos/interchain-security/issues/782
- [ ] https://github.com/cosmos/interchain-security/issues/885
- [ ] https://github.com/cosmos/interchain-security/issues/895
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/790
- [ ] https://github.com/cosmos/interchain-security/issues/780
- [ ] Various integration and UTs for things like endblockers, involving newly introduced code. Slashing edge cases, etc.
- [ ] https://github.com/cosmos/interchain-security/issues/894
- [ ] https://github.com/cosmos/interchain-security/issues/1069
```
