### ISSUE TITLE
EPIC: Split `go.mod` into multiple `go.mod`s

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#801]
# Problem

Currently ICS has a single `go.mod` which has golang dependancies for any code utilized by the provider module, the consumer module, and all tests therein. Ex: this can cause issues when we need to bump a dependancy for the consumer module, but not for the provider module.

# Closing criteria

Create multiple `go.mod`s, one for the provider module, one for the consumer module, and one for everything else (tests, common helpers, etc.). That way consumer chains will only need to worry about the dependancies contained within the consumer go.mod.

# Problem details

It's notable that releasing and branching are topics that are relevant to this issue.

Once we split out the go.mods in this repo, we would then have the option to split up how we do versioning for the provider and consumer modules.

Currently, everything is very monorepo-esq, in that a change to the provider module, consumer module, or protocol API, all follow the same semver rules, and increment the same running version of ICS. 

We could setup a versioning system where a provider-only change only bumps the provider version, same with consumer, and a protocol/api change would affect both the provider and consumer versions. 

Release branching would get tricky if this split out release system were to be built out, although it could be as simple as adding a branch prefix for the consumer vs provider version

# Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/pull/890 serves as experimentation and some of that work can be salvaged
- [ ] Refactor /x/ccv/types s.t. it doesn't have external package dependancies from this repo. Make sure x/ccv/types only contains code that is shared by consumer/provider (including .pb files)
- [ ] Refactor x/ccv/provider and x/ccv/consumer s.t. they only rely on x/ccv/types, not one another, and not any other packages from this repo (not even testutils for example)
- [ ] Add go.mods to the three directories in x/ccv, import dependancies should match what's described above
- [ ] Add documentation and guidelines around how consumer/provider semver can be completely separate. Make note that if the shared /x/ccv/types folder is changed (and new release is cut), that's the only scenario that a new release will be cut for both consumer/provider. Also update PR template to reflect this workflow
- [ ] Split out `make proto-gen` into `make proto-gen-provider`, `make proto-gen-consumer`, and `make proto-gen-types`
- [ ] https://github.com/cosmos/interchain-security/issues/889
```

```[tasklist]
### Nice to have

```

**Comment by smarshall-spitzbart** [comment]
Concrete example of where this split could help us. Consumers want sdk 47. It's more trivial to make this version bump for just the consumer module, rather than the entire repo (incl the provider module). If we had dependancies split into multiple go.mod's, we could have mismatched sdk versions for consumer and provider

**Comment by smarshall-spitzbart** [comment]
Current idea here is to have 4 go.mods. One for each of:
- ccv provider production code 
- ccv consumer production code
- proto files, proto generated code, and shared ccv helpers/types
- testing (e2e testing can be moved to it's own repo from this module)

Probably easiest if we start by separating out the proto module from the ccv modules.

CC @mpoke @MSalopek @sainoe lmk if you think I'm missing something here

**Comment by faddat** [comment]
Hey, I'd like to mention that I think that this is the wrong way to solve this problem. 

Instead, we can have 

```go
module github.com/cosmos/interchain-security/v2
```

v2 can then run tests against v1 and we do not need to inherit the workflow challenges of a multi-module repository.

**Comment by smarshall-spitzbart** [comment]
> Hey, I'd like to mention that I think that this is the wrong way to solve this problem.
> 
> Instead, we can have
> 
> ```go
> module github.com/cosmos/interchain-security/v2
> ```
> 
> v2 can then run tests against v1 and we do not need to inherit the workflow challenges of a multi-module repository.

This would work for docker testing, not in-mem testing that requires one version of sdk. A multi-module repository's main pro is giving us a more granular semver for consumer and provider separately

**Comment by faddat** [comment]
The in-memory testing can occur in its own module version path though?

**Comment by smarshall-spitzbart** [comment]
## Spike results

I explored this idea today with this [spike branch](https://github.com/cosmos/interchain-security/tree/shawn%2Fgo-mod-split-aug-spike). Here's my conclusions:

Splitting this repo to have multiple go.mods is possible. However there are various intricacies involved in decoupling the package hierarchy to have `x/ccv/types` as the lowest level dep, with `x/ccv/consumer` and `x/ccv/provider` being one dep layer above, with high-level tests depending on all three of the mentioned packages. I'd estimate this decoupling would take 2-5 workdays to finish, and require significant review effort.

## Why go.mod split is not the way to go

Let's take a step back and remember the issue we're trying to solve - **We need a clean way to decouple semver/releasing for the consumer and provider modules**. After more consideration, splitting up go.mods gives us little benefit in achieving this. Reasons:

- The `go.mod` dependency system is tied to git tags for the entire repo (ex: `require github.com/cometbft/cometbft v0.37.2` refers to a historical tag for the entire cometbft repo)
- It'd be an odd dev experience to allow modules to reference past releases of other modules in the same repo. When would we ever want the consumer module to reference a past release of the types module for example? 
- If we allow for `go.mod` replace statements to build from local source code, why split up the package deps at all?
- Splitting go.mods adds a bunch of complexity with `go.work` files and all that shiz. VSCode does not play well with multiple module repos either. 

## Why separate repos is cool but also not the way to go 

All this considered, the cleanest solution to decoupling semver/releasing for the consumer and provider modules would be to have multiple repos, each with their own go.mod (3-4 repos total including high level tests). With this scheme we could separately tag each repo as changes are merged, they could share some code from `types` being an external dep, etc.

I don't think any of us want to split up the monorepo, that's a lot of work and seems like bikeshedding. There's another solution that's very simple..  

## Proposed solution to decouple consumer and provider releasing/semver 

Maintain a separate release cycle for the consumer/provider modules without actually decoupling their deps. Ie. all new features are still built off and merged to main. There's still one top level go.mod. When we release, it's a tagged release that's intended to be used by consumers OR providers, BUT NEVER BOTH. New releases would be tagged as `consumer-v3.2.0`, `provider-v4.0.0`, etc. Release branches would be maintained as `release/consumer-v3.2.x`, `release/provider-v4.0.x`, etc.

Slightly adapting [the current semver ruleset](https://github.com/cosmos/interchain-security/blob/cca008d856e3ffc60ec1a486871d0faa702abe26/CONTRIBUTING.md#semantic-versioning):

- A library API breaking change TO EITHER MODULE will result in an increase of the MAJOR version number for both the consumer and provider modules. Most often this will involve bumping a major version of sdk or a large change to the protocol that warrants new a major version for consumer/provider anyways.  
- A state breaking change (change requiring coordinated upgrade and/or state migration) will result in an increase of the MINOR version number FOR THAT MODULE (consumer-x.Y.z or provider-x.Y.z ).
- Any other changes (including node API breaking changes) will result in an increase of the PATCH version number FOR THAT MODULE (consumer-x.y.Z or provider-x.y.Z).

For each PR merged to main (something like this should be in our PR template):

- If this PR is library API breaking, bump the go.mod version string of the repo, and the PR will result in a new major release for the consumer and provider. 
- Else if this PR is state breaking to consumer, provider, or both, the PR will accordingly result in new minor release(s). 
- Else if this PR has other changes, the PR will accordingly result in new minor release(s). 

## Why is this proposed solution useful?

- Consumer repos have clear communication of what tagged versions are relevant to them. Consumer devs should know to never reference an ICS version that starts with `provider`.
- Consumer and provider modules do not deviate as long as we continually release off a shared main branch
- No code changes, just changes in process. Very simple

## Side note

We should start a pattern of releasing a new consumer or provider version whenever a big change is merged to main, even if that release is unused at first. This should be a normal part of the dev process!

**Comment by smarshall-spitzbart** [comment]
Closing this issue, idea from my comment will be tracked by https://github.com/cosmos/interchain-security/issues/1216
