### ISSUE TITLE
Replicated Security soft opt-out

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#851]
# Problem

The current design of Replicated Security requires all validators to validate on all consumer chains. 

# Closing criteria

Soft opt-out is enabled --  allow the bottom x% of the validator set by power to opt out of validating consumer chains without being jailed or otherwise punished for it. 

# Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/765
- [ ] https://github.com/cosmos/interchain-security/issues/1000
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/893
- [ ] https://github.com/cosmos/interchain-security/issues/849
- [ ] test soft opt-out with diff testing
```
