### ISSUE TITLE
Upgrade CCV modules to SDK v0.47

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#852]
# Problem

Currently, the entire ICS code requires SDK v0.45 and IBC v4 which will soon reach EoL.
We want to support SDK v47 and IBC v7 to allow upgrading provider chains and onboarding new consumer chains.

# Closing criteria
- [x] provider code upgraded to required dependencies and API changes supported
- [x] provider code upgraded to required dependencies and API changes supported
- [x] unittests support required dependencies and are passing
- [x] integration, MBT tests support required dependencies and are passing
- [x] e2e tests support required dependencies and are passing
- [x] handle proto deps
- [ ] push protos to BSR
- [x] rework and add tests `AfterUnbondingInitiated` on provider side to support new cosmos-sdk behaviour
- [ ] support `CancelUnbond` operation on the provider (cosmos-sdk v47 related)

# Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/753
- [ ] https://github.com/cosmos/interchain-security/issues/942
- [ ] https://github.com/cosmos/interchain-security/issues/943
- [ ] https://github.com/cosmos/interchain-security/issues/947
- [ ] https://github.com/cosmos/interchain-security/issues/944
- [ ] https://github.com/cosmos/interchain-security/issues/948
- [ ] https://github.com/cosmos/interchain-security/issues/946
- [ ] https://github.com/cosmos/interchain-security/issues/945
- [ ] https://github.com/cosmos/interchain-security/issues/949
- [ ] add migration code
```

```[tasklist]
### Nice to have
- [ ] Refactor e2e testing framework to support testing ICS chains running different cosmos-sdk and IBC versions
- [ ] https://github.com/cosmos/interchain-security/issues/1008
```

**Comment by faddat** [comment]
* #817

**Comment by adizere** [comment]
> Also, we are going to upgrade the whole repository. We feel that it doesn't make sense to do it partially.

An experience we had from other repos (this is not about the Hub) is that feature branches could come in handy to help split large work in smaller PRs. We used a feature branch to capture a multi-month work related to ABCI 2.0, for example.

The gist of using feature branches: Small PRs target the longer-lived feature branch, and the feature branch may intermittently fail to lint/make/CI. It's important to scope each PRs and review them _as if it's landing on main_ with care. Eventually, you merge the whole feature branch into main when it's ready, and then it's still advised to do a sync review with 1-2 engineers. This is no silver bullet, and has some costs, but it has worked better than having big PRs.

**Comment by mpoke** [comment]
> > Also, we are going to upgrade the whole repository. We feel that it doesn't make sense to do it partially.
> 
> An experience we had from other repos (this is not about the Hub) is that feature branches could come in handy to help split large work in smaller PRs. We used a feature branch to capture a multi-month work related to ABCI 2.0, for example.
> 
> The gist of using feature branches: Small PRs target the longer-lived feature branch, and the feature branch may intermittently fail to lint/make/CI. It's important to scope each PRs and review them _as if it's landing on main_ with care. Eventually, you merge the whole feature branch into main when it's ready, and then it's still advised to do a sync review with 1-2 engineers. This is no silver bullet, and has some costs, but it has worked better than having big PRs.

Thank you @adizere. 

@faddat We are currently updating the guidelines for working on large contributions https://github.com/cosmos/interchain-security/pull/868. Constructive feedback from the community is greatly appreciated.

**Comment by faddat** [comment]
@mpoke sir, 

1) this repository is not meaningfully separate from the cosmos hub.  Doing serious work on the hub and promoting the use of the hub means doing work here. 

2) As you know, the "big PR policy" and contributors policy were just put here, by informal.  In countless code contributions with more teams than I can count across cosmos, I have never once read contributors guidelines, folks instead typically just give friendly feedback and we learn what the different teams want.

3) ICS is winning sir.  Congratulations. But that comes with its own set of challenges, and the first of these is apparently compatibility resource contention on the cosmos hub. Specifically the set of issues that I laid out in the google doc in the issue that you closed, and in slack, and in the hub-tech channel in the cosmos hub governance telegram, and you turned into an epic on ICS and on Gaia.

```markdown
@faddat Thank you for your contribution. In order for us to accept contributions, we need contributors to follow our contributing guidelines (see CONTRIBUTING.md in the root of the repo). The reason for this is, while others may submit these pull requests, our team is ultimately responsible for maintaining the code that gets merged and eventually released, meaning that our team needs as much context as possible on the nature of all of the changes being merged.

As such, for large/complex changes, we absolutely require up-front discussion in issues/GitHub discussions. In some cases, like this change, it would be preferable to even have synchronous design sessions to socialize a collective understanding of the nature of incoming changes prior to the work even starting.

Note that if someone from our team is assigned to a particular issue, we will most likely opt to not accept unsolicited PRs that attempt to address those same issues. As a general rule, if someone else is assigned to an issue and you would like to take it over, please reach out to that person and ask whether you can either collaborate with them on it or take it over.
```

4) I guess that this is good?  here's why:

Your commentary allows us to pinpoint the slowdown in supporting 47 and shows concretely that you are not interested in our help on the matter, and prefer a slower ship time to active and friendly collaboration.  It is also how forks happen, and I do not want to have an ics fork. So I want to tell you about market demand -- people definitely want to use ICS, and they want to build things on the hub and that is GLORIOUS and a big accomplishment for yourself and your team.  When they attempt to build things using ics, however, they run into difficulties:

* spm
* outdated ibc-go import
* sdk fork 
  * please do answer the question that we've been discussing with your team members since March 23, 2023: do we need to fork the sdk to do 47.  Our team thinks that the answer is yes, and we have gotten different answers from different people at informal.
    * if the answer is yes, that's totally fine -- we should put together a description of the changes needed and then check upstream w/ the sdk team to see if they are breaking changes or not.  I reckon that they would reject breaking changes, and accept non-breaking changes. 
    * if no, then we will need to have a call with your team to discuss, because our findings have been pretty clear. 

As you are aware, on Thursday, March 23rd, Jehan discussed the appropriate plan and style for an sdk 47 upgrade wth me.

**Comment by faddat** [comment]
* https://github.com/cosmos/interchain-security/issues/874

**Comment by faddat** [comment]
This is the item that we most urgently need feedback on:

* https://github.com/cosmos/cosmos-sdk/pull/15917

the question is: does upgrading to sdk 47 require using a forked version of sdk 47?

thanks

**Comment by mpoke** [comment]
> This is the item that we most urgently need feedback on:
> 
> * [fix: changes to sdk for interchain security cosmos-sdk#15917](https://github.com/cosmos/cosmos-sdk/pull/15917)
> 
> the question is: does upgrading to sdk 47 require using a forked version of sdk 47?
> 
> thanks

@faddat I believe that [this comment](https://github.com/cosmos/cosmos-sdk/pull/15917#issuecomment-1519540368) addresses your concern.

**Comment by mpoke** [comment]
> **finally, i must say that it is simply not good to block work on simple stuff, like the questions we've been asking for a very long time now, including in this issue, which you've chosen not to answer**
> 
> 1. @vuong177 found that it is necessary to use a forked cosmos-sdk v0.47.x -- do you agree, or nah?  in either case, what are your thoughts on the matter?
> 2. We also came up with the idea of adding some things to ibc-go, reducing the amount of boilerplate that we need to copy into this repo from ibc.  Do you agree, or nah?  In either case, what are your thoughts on the matter?

@faddat Thank you for sharing your feedback. If you have concerns or you see any issues regarding Interchain Security, please open a new issue (if one is not already opened) and participate in thoughtful discussion on that issue. We'll try to address your concerns as soon as possible. 

Regarding the first point, you have received immediate feedback on both PRs you have opened on the SDK repo: https://github.com/cosmos/cosmos-sdk/pull/15856 and https://github.com/cosmos/cosmos-sdk/pull/15917.

Regarding the second point, I need more context? That's the reason we are working with issues with a clear problem description where we can have thorough discussions.

**Comment by mpoke** [comment]
> 1. this repository is not meaningfully separate from the cosmos hub.  Doing serious work on the hub and promoting the use of the hub means doing work here.
> 2. As you know, the "big PR policy" and contributors policy were just put here, by informal.  In countless code contributions with more teams than I can count across cosmos, I have never once read contributors guidelines, folks instead typically just give friendly feedback and we learn what the different teams want.

@faddat Thank you for your feedback. As these topics are not concerning the current issue, please start a [new discussion](https://github.com/cosmos/interchain-security/discussions/new/choose) or open a [new issue](https://github.com/cosmos/interchain-security/issues/new/choose). We'll gladly address your concerns there.

**Comment by faddat** [comment]
Sir, we really don't know what to do anymore. This is a uniquely challenging situation, and it seems that you refuse to have the necessary conversation, and is it at all possible for you to answer the question about the SDK? Thank you so much. We believe that it is an essential blocker to 47 on the hub.

**Comment by jtremback** [comment]
Hi Jacob. We originally removed the 3 lines performing a public key check in `HandleValidatorSignature` in `infractions.go` in from cosmos-sdk around a year ago. Apparently, somehow the public key snuck back into 47.

A few weeks ago, Stride ran into the public key check, but fixed it [by removing `HandleValidatorSignature`](https://github.com/Stride-Labs/interchain-security/blame/consumer_sdk_upgrade_v047_disable_test/x/ccv/democracy/slashing/module.go#L46).

Many people have found this issue, which to reiterate, is that the cosmos-sdk team accidentally put 3 lines back into 47 which were not in 45.15-ics.

Which other issues did you identify?

**Comment by faddat** [comment]
Look at our PR

We have been trying to work with your team on this for over a month.

You guys have actually changed the rules on this repository to make it more difficult for us to contribute.

During that time you have allowed us to do all of the work on the upgrade while taking it.
