### ISSUE TITLE
EPIC: Partial Set Security

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#853]
# Problem

This is a meta issue to track the work on opt-in security. With opt in security, validators will be able to decide which consumer chains they would like to validate on, and will only receive rewards for those that they are active on.

EDIT: Renamed to Partial Set Security. See this [doc](https://informalsystems.notion.site/Partial-Set-Security-398ca9a1453740068be5c7964a4059bb) for a high level design. 

# Closing criteria

Partial Set Security is implemented.

# Task list

```[tasklist]
### Must have
- [x] Analysis of whether "governance fraud proofs" are Ok
- [ ] https://github.com/cosmos/interchain-security/issues/788
- [ ] https://github.com/cosmos/interchain-security/issues/1571
- [ ] https://github.com/cosmos/interchain-security/issues/1587
- [ ] https://github.com/cosmos/interchain-security/issues/1586
- [ ] https://github.com/cosmos/interchain-security/issues/1574
- [ ] https://github.com/cosmos/interchain-security/issues/1606
- [ ] https://github.com/cosmos/interchain-security/issues/1607
- [ ] https://github.com/cosmos/interchain-security/issues/1588
- [ ] https://github.com/cosmos/interchain-security/issues/1610
- [ ] https://github.com/cosmos/interchain-security/issues/1611
- [ ] https://github.com/cosmos/interchain-security/issues/1609
- [ ] https://github.com/cosmos/interchain-security/issues/1608
- [ ] https://github.com/cosmos/interchain-security/issues/1630
- [ ] https://github.com/cosmos/interchain-security/issues/1633
- [ ] https://github.com/cosmos/interchain-security/issues/1658
- [ ] Migrate Neutron and Stride to Top N with N = 95 or N = 100? When we build `gaia` v17
- [ ] https://github.com/cosmos/interchain-security/issues/1707
- [ ] https://github.com/cosmos/interchain-security/issues/1697
- [ ] https://github.com/cosmos/interchain-security/issues/1781
- [ ] https://github.com/cosmos/interchain-security/issues/1772
- [ ] https://github.com/cosmos/interchain-security/issues/1785
- [ ] https://github.com/cosmos/interchain-security/issues/1245
- [ ] https://github.com/cosmos/interchain-security/issues/1926
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/1634
- [ ] https://github.com/cosmos/interchain-security/issues/1635
- [ ] https://github.com/cosmos/interchain-security/issues/894
- [ ] Enable fraud votes
```

**Comment by mpoke** [comment]
Putting this work on hold as the following tasks are very likely needed to enable opt-in security:

- cryptographic equivocation https://github.com/cosmos/interchain-security/issues/732
- redesigning ICS as a read-only protocol https://github.com/cosmos/interchain-security/issues/1293
