### ISSUE TITLE
Write differential testing driver using ibc-go framework

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#87]
# Idea

A driver will be needed for [differential testing](https://github.com/cosmos/interchain-security/issues/60). For the first application, the driver should have the actions [outlined by Marius](https://github.com/cosmos/interchain-security/issues/60#issuecomment-1109952294) and should orchestrate the system in memory using ibc-go/testing.

In particular the actions are

> 
> - on provider 
>   - delegate(D, V, A), where D is a delegator, V is a validator and A is an amount
>   - undelegate(D, V, A)
>   - redelegate(D, Vsrc, Vdst, A)
>   - slash(V, infractionHeight, slashFactor)
>   - jumpToBlock(h), where h is a height larger than the current height
> - on consumer
>   - slash(V, infractionHeight, slashFactor)
>   - jumpToBlock(h)

## Tasks

- [x] Locate the code locations where these abstract actions can be called
- [x] Write a driver using ibc-go/testing to call these actions
- [ ] Write some input traces by hand to check if the driver is sensible

## Resources

- Parent issue: https://github.com/cosmos/interchain-security/issues/60
- Sibling issue: https://github.com/cosmos/interchain-security/issues/88
