### ISSUE TITLE
Write reference implementation to generate traces for differential testing

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#88]
# Idea

A reference implementation will be needed for [differential testing](https://github.com/cosmos/interchain-security/issues/60). For the first application of differential testing the implementation should have the actions [outlined by Marius](https://github.com/cosmos/interchain-security/issues/60#issuecomment-1109952294).

In particular the actions are

> 
> - on provider 
>   - delegate(D, V, A), where D is a delegator, V is a validator and A is an amount
>   - undelegate(D, V, A)
>   - redelegate(D, Vsrc, Vdst, A)
>   - slash(V, infractionHeight, slashFactor)
>   - jumpToBlock(h), where h is a height larger than the current height
> - on consumer
>   - slash(V, infractionHeight, slashFactor)
>   - jumpToBlock(h)

## Tasks

- [ ] Finish the sibling issue: https://github.com/cosmos/interchain-security/issues/87
- [x] Write the model/implementation
- [x] Generate simple/dumb/random traces

I will create a new issue  when this is complete to create and test traces in a smarter way.

## Resources

- Parent issue: https://github.com/cosmos/interchain-security/issues/60
- Sibling issue: https://github.com/cosmos/interchain-security/issues/87
