### ISSUE TITLE
EPIC: Implement and integrate CometMock

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#932]
# Problem

We would like to mock out CometBFT in our end-to-end tests, since we
want to test the underlying application, but we do not care about actually running
a replicated state machine resistant to byzantine faults - just running a state machine is enough for testing.
Mocking out the consensus layer means we can skip
waiting for the network communication in the potentially multiple rounds
needed for CometBFT to come to consensus.
Thus, this can make the existing tests which are running full nodes faster.

Looking further, it can also enable writing tests with new functionality,
as CometMock can mock arbitrary timestamps coming from Comet,
and we can finely control which validators sign and don't sign which blocks.

# Closing criteria

CometMock has been implemented in a proper repository.
It is integrated in our CI pipeline(s) and covers all common usecases
in a way that is delightful to use.

# Problem details

# Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/interchain-security/issues/935
- [ ] https://github.com/cosmos/interchain-security/issues/938
- [ ] https://github.com/cosmos/interchain-security/issues/1006
- [ ] https://github.com/cosmos/interchain-security/issues/1248
- [ ] https://github.com/cosmos/interchain-security/issues/1182
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/937
- [ ] https://github.com/cosmos/interchain-security/issues/936
```
